import { config } from 'dotenv';
import { connectDb } from '../lib/db.js';
import Coupon from '../models/coupon.model.js';

config();

const seedCoupon = [
  {
    coupon_id: 'CPN001',
    user_type: 'new_user',
    code: 'WELCOME50',
    description: 'Get 50% off for new users',
    discount_type: 'percentage',
    discount_value: '50',
    min_order_value: '200',
    valid_from: '2025-05-01',
    valid_till: '2025-06-01',
    platforms: ['Zomato', 'Swiggy'],
    usage_limit: '1',
    is_active: true,
  },
  {
    coupon_id: 'CPN002',
    user_type: 'existing_user',
    code: 'SAVE20',
    description: 'Save ₹20 on your next order',
    discount_type: 'flat',
    discount_value: '20',
    min_order_value: '100',
    valid_from: '2025-05-01',
    valid_till: '2025-05-31',
    platforms: ['Zomato'],
    usage_limit: '2',
    is_active: true,
  },
  {
    coupon_id: 'CPN003',
    user_type: 'new_user',
    code: 'NEW30',
    description: 'Flat ₹30 off for new users',
    discount_type: 'flat',
    discount_value: '30',
    min_order_value: '150',
    valid_from: '2025-05-05',
    valid_till: '2025-06-05',
    platforms: ['Swiggy'],
    usage_limit: '1',
    is_active: true,
  },
  {
    coupon_id: 'CPN004',
    user_type: 'existing_user',
    code: 'FESTIVE10',
    description: '10% off during festive season',
    discount_type: 'percentage',
    discount_value: '10',
    min_order_value: '300',
    valid_from: '2025-05-10',
    valid_till: '2025-06-10',
    platforms: ['Zomato', 'Swiggy'],
    usage_limit: '3',
    is_active: true,
  },
  {
    coupon_id: 'CPN005',
    user_type: 'all',
    code: 'MEAL25',
    description: '25% off on meal orders',
    discount_type: 'percentage',
    discount_value: '25',
    min_order_value: '250',
    valid_from: '2025-05-01',
    valid_till: '2025-05-20',
    platforms: ['Swiggy'],
    usage_limit: '1',
    is_active: false,
  },
  {
    coupon_id: 'CPN006',
    user_type: 'existing_user',
    code: 'DINNER15',
    description: '₹15 off on dinner orders',
    discount_type: 'flat',
    discount_value: '15',
    min_order_value: '120',
    valid_from: '2025-05-01',
    valid_till: '2025-05-31',
    platforms: ['Zomato'],
    usage_limit: '5',
    is_active: true,
  },
  {
    coupon_id: 'CPN007',
    user_type: 'new_user',
    code: 'TRYUS100',
    description: '₹100 off for first-time orders',
    discount_type: 'flat',
    discount_value: '100',
    min_order_value: '400',
    valid_from: '2025-04-20',
    valid_till: '2025-05-20',
    platforms: ['Zomato', 'Swiggy'],
    usage_limit: '1',
    is_active: true,
  },
  {
    coupon_id: 'CPN008',
    user_type: 'all',
    code: 'WEEKEND20',
    description: '20% off on weekend orders',
    discount_type: 'percentage',
    discount_value: '20',
    min_order_value: '200',
    valid_from: '2025-05-01',
    valid_till: '2025-05-30',
    platforms: ['Zomato'],
    usage_limit: '2',
    is_active: true,
  },
  {
    coupon_id: 'CPN009',
    user_type: 'existing_user',
    code: 'LOYALTY50',
    description: '50% off for loyal users',
    discount_type: 'percentage',
    discount_value: '50',
    min_order_value: '300',
    valid_from: '2025-05-01',
    valid_till: '2025-06-15',
    platforms: ['Swiggy'],
    usage_limit: '1',
    is_active: true,
  },
  {
    coupon_id: 'CPN010',
    user_type: 'all',
    code: 'HUNGRY30',
    description: "Flat ₹30 off when you're hungry!",
    discount_type: 'flat',
    discount_value: '30',
    min_order_value: '150',
    valid_from: '2025-05-01',
    valid_till: '2025-06-01',
    platforms: ['Zomato', 'Swiggy'],
    usage_limit: '4',
    is_active: true,
  },
];

const seedDatabase = async () => {
  try {
    await connectDb();
    await Coupon.insertMany(seedCoupon);
    console.log('Data added');
  } catch (error) {
    console.error('Error while data adding', error);
  }
};

seedDatabase();
