import { config } from 'dotenv';
import { connectDb } from '../lib/db.js';
import restaurantList from '../models/restaurantList.model.js';

config();

const seedRestaurant = [
  {
    restaurant_id: 'R300',
    restaurant_name: 'Spice Villa',
    cuisine: 'Indian',
    location: 'Greater Noida',
    rating: 4.0,
    offer: 'Buy 1 Get 1',
    distance: 2.8,
    img_url: 'https://example.com/images/restaurant_1.jpg',
  },
  {
    restaurant_id: 'R301',
    restaurant_name: 'Urban Tandoor',
    cuisine: 'Indian',
    location: 'Greater Noida',
    rating: 3.7,
    offer: '50% off',
    distance: 5.3,
    img_url: 'https://example.com/images/restaurant_2.jpg',
  },
  {
    restaurant_id: 'R302',
    restaurant_name: 'Burger Craze',
    cuisine: 'Indian',
    location: 'Greater Noida',
    rating: 4.0,
    offer: 'Free Topping',
    distance: 2.3,
    img_url: 'https://example.com/images/restaurant_3.jpg',
  },
  {
    restaurant_id: 'R303',
    restaurant_name: 'Tandoori Nights',
    cuisine: 'Italian',
    location: 'Greater Noida',
    rating: 4.5,
    offer: '50% off',
    distance: 2.4,
    img_url: 'https://example.com/images/restaurant_4.jpg',
  },
  {
    restaurant_id: 'R304',
    restaurant_name: 'Pizza Italiano',
    cuisine: 'Healthy',
    location: 'Greater Noida',
    rating: 4.9,
    offer: '30% off',
    distance: 2.1,
    img_url: 'https://example.com/images/restaurant_5.jpg',
  },
  {
    restaurant_id: 'R305',
    restaurant_name: 'Sushi Zen',
    cuisine: 'Mexican',
    location: 'Greater Noida',
    rating: 4.8,
    offer: '20% off',
    distance: 6.5,
    img_url: 'https://example.com/images/restaurant_6.jpg',
  },
  {
    restaurant_id: 'R306',
    restaurant_name: 'Green Bowl',
    cuisine: 'Italian',
    location: 'Greater Noida',
    rating: 3.7,
    offer: '30% off',
    distance: 6.2,
    img_url: 'https://example.com/images/restaurant_7.jpg',
  },
  {
    restaurant_id: 'R307',
    restaurant_name: 'Dragon Wok',
    cuisine: 'Mexican',
    location: 'Greater Noida',
    rating: 4.6,
    offer: '20% off',
    distance: 7.3,
    img_url: 'https://example.com/images/restaurant_8.jpg',
  },
  {
    restaurant_id: 'R308',
    restaurant_name: 'Waffle World',
    cuisine: 'Mexican',
    location: 'Greater Noida',
    rating: 4.1,
    offer: '30% off',
    distance: 7.4,
    img_url: 'https://example.com/images/restaurant_9.jpg',
  },
  {
    restaurant_id: 'R309',
    restaurant_name: 'Caf\u00e9 Mocha',
    cuisine: 'Japanese',
    location: 'Greater Noida',
    rating: 4.1,
    offer: '20% off',
    distance: 6.8,
    img_url: 'https://example.com/images/restaurant_10.jpg',
  },
  {
    restaurant_id: 'R310',
    restaurant_name: 'Noodle House',
    cuisine: 'American',
    location: 'Greater Noida',
    rating: 4.0,
    offer: '10% Cashback',
    distance: 1.6,
    img_url: 'https://example.com/images/restaurant_11.jpg',
  },
  {
    restaurant_id: 'R311',
    restaurant_name: 'Biryani Blues',
    cuisine: 'Street Food',
    location: 'Greater Noida',
    rating: 3.5,
    offer: '10% Cashback',
    distance: 3.5,
    img_url: 'https://example.com/images/restaurant_12.jpg',
  },
  {
    restaurant_id: 'R312',
    restaurant_name: 'The Curry Pot',
    cuisine: 'Japanese',
    location: 'Greater Noida',
    rating: 4.8,
    offer: '20% off',
    distance: 5.8,
    img_url: 'https://example.com/images/restaurant_13.jpg',
  },
  {
    restaurant_id: 'R313',
    restaurant_name: 'Taco Town',
    cuisine: 'Italian',
    location: 'Greater Noida',
    rating: 3.6,
    offer: 'Free Topping',
    distance: 7.8,
    img_url: 'https://example.com/images/restaurant_14.jpg',
  },
  {
    restaurant_id: 'R314',
    restaurant_name: 'Wrap It Up',
    cuisine: 'Healthy',
    location: 'Greater Noida',
    rating: 3.6,
    offer: 'Free Delivery',
    distance: 3.8,
    img_url: 'https://example.com/images/restaurant_15.jpg',
  },
  {
    restaurant_id: 'R315',
    restaurant_name: 'Sandwich Hub',
    cuisine: 'American',
    location: 'Greater Noida',
    rating: 4.2,
    offer: 'Free Dessert',
    distance: 2.6,
    img_url: 'https://example.com/images/restaurant_16.jpg',
  },
  {
    restaurant_id: 'R316',
    restaurant_name: 'Pasta Bay',
    cuisine: 'Mughlai',
    location: 'Greater Noida',
    rating: 4.0,
    offer: 'Buy 1 Get 1',
    distance: 3.3,
    img_url: 'https://example.com/images/restaurant_17.jpg',
  },
  {
    restaurant_id: 'R317',
    restaurant_name: 'Chaat Bazaar',
    cuisine: 'Italian',
    location: 'Greater Noida',
    rating: 4.7,
    offer: 'Free Delivery',
    distance: 7.2,
    img_url: 'https://example.com/images/restaurant_18.jpg',
  },
  {
    restaurant_id: 'R318',
    restaurant_name: 'Roll Nation',
    cuisine: 'American',
    location: 'Greater Noida',
    rating: 3.7,
    offer: '20% off',
    distance: 7.0,
    img_url: 'https://example.com/images/restaurant_19.jpg',
  },
  {
    restaurant_id: 'R319',
    restaurant_name: 'Momo Station',
    cuisine: 'Chinese',
    location: 'Greater Noida',
    rating: 4.1,
    offer: '20% off',
    distance: 2.0,
    img_url: 'https://example.com/images/restaurant_20.jpg',
  },
];

const seedDatabase = async () => {
  try {
    await connectDb();
    await restaurantList.insertMany(seedRestaurant);
    console.log('Database seeded successfully');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
};

seedDatabase();
